query GetStreamQueue($tournamentId: ID!) {
  streamQueue(tournamentId: $tournamentId) {
    id
    stream {
      id
      streamSource
      streamName
      streamGame
      streamStatus
      isOnline
      enabled
    }
    sets {
      id
      identifier
      round
      fullRoundText
      state
      startedAt
      completedAt
      winnerId
      displayScore
      totalGames
      vodUrl
      phaseGroup {
        id
        displayIdentifier
        phase {
          id
          name
        }
      }
      slots {
        slotIndex
        entrant {
          id
          name
          initialSeedNum
          isDisqualified
          participants {
            player {
              id
              gamerTag
              prefix
            }
          }
        }
        standing {
          placement
          stats {
            score {
              label
              value
              displayValue
            }
          }
        }
      }
    }
  }
}
